<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\V0XCleaner.Core\V0XCleaner.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>V0XCleaner.ElevatedHelper</AssemblyName>
    <RootNamespace>V0XCleaner.ElevatedHelper</RootNamespace>
    <Product>V0X Cleaner - Assistant d'élévation</Product>
    <Company>V0X</Company>
    <Version>0.2.0</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
